# Generated by Django 2.2.2 on 2020-01-23 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 21, 12, 54, 883870)),
        ),
    ]
