# Generated by Django 2.2.2 on 2020-01-23 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200123_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 22, 2, 53, 416918)),
        ),
    ]
