# Generated by Django 2.2.2 on 2020-07-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200318_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
