# Generated by Django 2.2.2 on 2020-07-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='users',
            new_name='user',
        ),
    ]
